import type { RecommendationItem } from './contracts'

// Fictional, fixed fixtures. No live jobs, profile extraction or ranking is implied.
const fetchedAt = '2026-10-01T08:00:00Z'

export const demoJobs: RecommendationItem[] = [
  {
    job: {
      job_id: 'demo-1',
      source: 'JobScout 示例库',
      source_url: 'https://example.com/jobs/1',
      source_links: ['https://example.com/jobs/1', 'https://example.com/careers/1'],
      title: '初级前端工程师',
      company: 'Mint Studio · 示例公司',
      location: '香港',
      salary: 'HK$ 22,000–28,000 / 月',
      target_direction: '前端开发',
      responsibilities: [
        '参与 Web 产品的界面开发与交互优化',
        '与设计师协作，搭建可复用的组件和响应式页面',
      ],
      required_skills: ['React', 'TypeScript', 'CSS', 'Git'],
      posted_at: '2026-09-28T08:00:00Z',
      expiry_at: null,
      fetched_at: fetchedAt,
      freshness_status: 'unknown',
    },
    missing_skills: ['自动化测试'],
    preparation_suggestions: [
      '准备一个可在线演示的 React 项目，说明组件设计思路。',
      '为核心交互补充测试，熟悉常见的异步请求与错误处理。',
    ],
  },
  {
    job: {
      job_id: 'demo-2',
      source: 'JobScout 示例库',
      source_url: 'https://example.com/jobs/2',
      source_links: [],
      title: '数据分析实习生',
      company: 'Peach Analytics · 示例公司',
      location: '香港',
      salary: 'HK$ 10,000–14,000 / 月',
      target_direction: '数据分析',
      responsibilities: ['清洗业务数据并制作分析报表', '通过可视化向团队说明业务趋势'],
      required_skills: ['Python', 'SQL', 'Excel'],
      posted_at: '2026-09-29T08:00:00Z',
      expiry_at: null,
      fetched_at: fetchedAt,
      freshness_status: 'active',
    },
    missing_skills: ['Tableau'],
    preparation_suggestions: ['使用公开数据完成一个分析案例，展示数据清洗、分析与可视化过程。'],
  },
  {
    job: {
      job_id: 'demo-3',
      source: 'JobScout 示例库',
      source_url: 'https://example.com/jobs/3',
      source_links: [],
      title: '产品设计实习生',
      company: 'Little Orbit · 示例公司',
      location: '深圳',
      salary: null,
      target_direction: '产品设计',
      responsibilities: ['协助用户访谈与竞品研究', '制作交互原型并维护设计规范'],
      required_skills: ['Figma', '交互设计', '用户研究'],
      posted_at: null,
      expiry_at: null,
      fetched_at: fetchedAt,
      freshness_status: 'unknown',
    },
    missing_skills: ['用户访谈'],
    preparation_suggestions: ['在作品集中补充从用户问题到设计决策的过程，解释迭代依据。'],
  },
  {
    job: {
      job_id: 'demo-4',
      source: 'JobScout 示例库',
      source_url: 'https://example.com/jobs/4',
      source_links: [],
      title: 'Web 开发实习生',
      company: 'Bloom Digital · 示例公司',
      location: '远程',
      salary: 'HK$ 12,000–16,000 / 月',
      target_direction: '前端开发',
      responsibilities: ['开发活动页面并优化移动端体验', '协助排查浏览器兼容性和无障碍问题'],
      required_skills: ['JavaScript', 'HTML', 'CSS'],
      posted_at: '2026-09-25T08:00:00Z',
      expiry_at: null,
      fetched_at: fetchedAt,
      freshness_status: 'active',
    },
    missing_skills: ['无障碍实践'],
    preparation_suggestions: ['检查个人项目的键盘导航、表单标签和颜色对比度。'],
  },
  {
    job: {
      job_id: 'demo-5',
      source: 'JobScout 示例库',
      source_url: 'https://example.com/jobs/5',
      source_links: [],
      title: '商业分析助理',
      company: 'Sunday Lab · 示例公司',
      location: '香港',
      salary: null,
      target_direction: '数据分析',
      responsibilities: ['整理市场调研信息并维护业务指标', '支持团队制作月度经营分析报告'],
      required_skills: ['Excel', 'SQL', '沟通表达'],
      posted_at: '2026-08-01T08:00:00Z',
      expiry_at: '2026-09-01T08:00:00Z',
      fetched_at: fetchedAt,
      freshness_status: 'expired',
    },
    missing_skills: [],
    preparation_suggestions: ['该示例已过期，用于展示时效状态；请优先关注其他岗位。'],
  },
]
