/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceNewRouteImport } from './routes/_workspace.new'
import { Route as WorkspaceSavedRouteImport } from './routes/_workspace.saved'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceSearchesSessionIdRouteImport } from './routes/_workspace.searches.$sessionId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceNewRoute = WorkspaceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSavedRoute = WorkspaceSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSearchesSessionIdRoute =
  WorkspaceSearchesSessionIdRouteImport.update({
    id: '/searches/$sessionId',
    path: '/searches/$sessionId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/login': typeof LoginRoute
  '/new': typeof WorkspaceNewRoute
  '/saved': typeof WorkspaceSavedRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/searches/$sessionId': typeof WorkspaceSearchesSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/new': typeof WorkspaceNewRoute
  '/saved': typeof WorkspaceSavedRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/': typeof WorkspaceIndexRoute
  '/searches/$sessionId': typeof WorkspaceSearchesSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/new': typeof WorkspaceNewRoute
  '/_workspace/saved': typeof WorkspaceSavedRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/searches/$sessionId': typeof WorkspaceSearchesSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/new' | '/saved' | '/settings' | '/searches/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/new' | '/saved' | '/settings' | '/' | '/searches/$sessionId'
  id:
    | '__root__'
    | '/_workspace'
    | '/login'
    | '/_workspace/new'
    | '/_workspace/saved'
    | '/_workspace/settings'
    | '/_workspace/'
    | '/_workspace/searches/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/new': {
      id: '/_workspace/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof WorkspaceNewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/saved': {
      id: '/_workspace/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof WorkspaceSavedRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/searches/$sessionId': {
      id: '/_workspace/searches/$sessionId'
      path: '/searches/$sessionId'
      fullPath: '/searches/$sessionId'
      preLoaderRoute: typeof WorkspaceSearchesSessionIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceNewRoute: typeof WorkspaceNewRoute
  WorkspaceSavedRoute: typeof WorkspaceSavedRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceSearchesSessionIdRoute: typeof WorkspaceSearchesSessionIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceNewRoute: WorkspaceNewRoute,
  WorkspaceSavedRoute: WorkspaceSavedRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceSearchesSessionIdRoute: WorkspaceSearchesSessionIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
