/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceNewRouteImport } from './routes/_workspace.new'
import { Route as WorkspaceProfileRouteImport } from './routes/_workspace.profile'
import { Route as WorkspaceSavedRouteImport } from './routes/_workspace.saved'
import { Route as WorkspaceTrackedRouteImport } from './routes/_workspace.tracked'
import { Route as WorkspaceSearchesSessionIdRouteImport } from './routes/_workspace.searches.$sessionId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceNewRoute = WorkspaceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSavedRoute = WorkspaceSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTrackedRoute = WorkspaceTrackedRouteImport.update({
  id: '/tracked',
  path: '/tracked',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSearchesSessionIdRoute =
  WorkspaceSearchesSessionIdRouteImport.update({
    id: '/searches/$sessionId',
    path: '/searches/$sessionId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/new': typeof WorkspaceNewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/saved': typeof WorkspaceSavedRoute
  '/tracked': typeof WorkspaceTrackedRoute
  '/searches/$sessionId': typeof WorkspaceSearchesSessionIdRoute
}
export interface FileRoutesByTo {
  '/new': typeof WorkspaceNewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/saved': typeof WorkspaceSavedRoute
  '/tracked': typeof WorkspaceTrackedRoute
  '/': typeof WorkspaceIndexRoute
  '/searches/$sessionId': typeof WorkspaceSearchesSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/new': typeof WorkspaceNewRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/saved': typeof WorkspaceSavedRoute
  '/_workspace/tracked': typeof WorkspaceTrackedRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/searches/$sessionId': typeof WorkspaceSearchesSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/new' | '/profile' | '/saved' | '/tracked' | '/searches/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/new' | '/profile' | '/saved' | '/tracked' | '/' | '/searches/$sessionId'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/new'
    | '/_workspace/profile'
    | '/_workspace/saved'
    | '/_workspace/tracked'
    | '/_workspace/'
    | '/_workspace/searches/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/new': {
      id: '/_workspace/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof WorkspaceNewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/saved': {
      id: '/_workspace/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof WorkspaceSavedRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/tracked': {
      id: '/_workspace/tracked'
      path: '/tracked'
      fullPath: '/tracked'
      preLoaderRoute: typeof WorkspaceTrackedRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/searches/$sessionId': {
      id: '/_workspace/searches/$sessionId'
      path: '/searches/$sessionId'
      fullPath: '/searches/$sessionId'
      preLoaderRoute: typeof WorkspaceSearchesSessionIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceNewRoute: typeof WorkspaceNewRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspaceSavedRoute: typeof WorkspaceSavedRoute
  WorkspaceTrackedRoute: typeof WorkspaceTrackedRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceSearchesSessionIdRoute: typeof WorkspaceSearchesSessionIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceNewRoute: WorkspaceNewRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspaceSavedRoute: WorkspaceSavedRoute,
  WorkspaceTrackedRoute: WorkspaceTrackedRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceSearchesSessionIdRoute: WorkspaceSearchesSessionIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
